<<<<<<< HEAD
# Your local pipeline config
trigger:
  branches:
    include:
      - main
=======
# Remote pipeline config from GitHub
trigger:
  branches:
    include:
      - master
>>>>>>> origin/main
