trigger:
- main  # Trigger the pipeline when changes are pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu virtual machine for the build agent

steps:
- task: UseJavaToolInstaller@0
  inputs:
    versionSpec: '1.8'  # Java version to be used in the pipeline (you can change to '11' or other versions)
    addToPath: true

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # The path to your Maven pom.xml file
    goals: 'clean install'  # Build goal for Maven (you can add 'test' if needed)
    options: '-X'  # Additional options for Maven (optional)

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'drop'  # Name of the build artifact (can be anything)
    publishLocation: 'Container'  # Specify that the artifact is stored in Azure DevOps storage
